name: BedWars
api-version: '1.13'
version: ${project.version}
author: Shizoukia, andrei1058
description: Origin BedWars minigame by andrei1058. customization by Shizoukia.
main: com.andrei1058.bedwars.BedWars
softdepend: [Vault,PlaceholderAPI,Citizens,Parties,SlimeWorldManager,VipFeatures,Enhanced-SlimeWorldManager,PartyAndFriends,Spigot-Party-API-PAF]
load: STARTUP
